### ISSUE TITLE
Doesn't work with latest Google Cal (fix included)

### ISSUE THREAD

**Issue by datavirtuoso** [robin-drexler/Google-Calendar-Guests-Can-Modify-Event-By-Default#1]
Hello, thanks for creating this. I found that it doesn't to work with the latest Google Calendar. If you change the following line it will fix things though:

from:
    var modifyEventCheckbox = document.querySelector('input[id$=guests-modify]');
to:
    var modifyEventCheckbox = document.querySelector("input[id$='guests-modify']");

Thanks!

**Comment by robin-drexler** [comment]
Hey, 
thanks for reporting. 

It's still working for me, though.
Which version of Chrome are you running?
Did you end up in some Google Calenda a/b test with a different UI than usual? :D

**Comment by datavirtuoso** [comment]
No problem. Thanks for writing this. I'm running Version 60.0.3112.101 (Official Build) (64-bit) on OSX Sierra.

The element looks like this:
<label><input type="checkbox" id=":1cguests-modify">modify event</label>

Thanks!

**Comment by gabro** [comment]
The new was UI officially announced yesterday and I can confirm the extension doesn't currently work.

**Comment by robin-drexler** [comment]
This extension is now obsolete, as the new calendar now supports setting this as default. :)

![image](https://user-images.githubusercontent.com/474248/31768140-4ad2bb1a-b4ce-11e7-823b-d7b7c1885b50.png)

**Comment by gabro** [comment]
Yay, I noticed that! 🎉 Thanks for the extension, it's been very useful so far! :)

**Comment by robin-drexler** [comment]
Thanks! Glad it was of use for you. :)
I'll close this issue as it's been resolved by Google. 💃
